# Generated by Django 4.1.3 on 2022-11-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_plublic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cover/%Y/%m/%d', verbose_name='cover')),
                ('creator_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='photographer name')),
                ('creator_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='photographer profile url')),
                ('sha_256', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='sha_256')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/%Y/%m/%d', verbose_name='cover')),
                ('slug', models.CharField(blank=True, max_length=256, null=True)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('publish', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('total_likes', models.PositiveIntegerField(db_index=True, default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='accounts.profile', verbose_name='author')),
            ],
            options={
                'ordering': ('-publish',),
                'get_latest_by': ['id'],
            },
        ),
    ]
