# Generated by Django 4.1.3 on 2022-11-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_category_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_plublic',
            new_name='is_public',
        ),
    ]
