# Generated by Django 4.1.3 on 2022-11-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='users/default.webp', null=True, upload_to='users/%Y/%m/%d', verbose_name='photo')),
                ('about', models.CharField(blank=True, max_length=150, null=True, verbose_name='about')),
                ('timezone', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('similar_post', models.BooleanField(default=True)),
            ],
        ),
    ]
